// <auto-generated />
using System;
using FoundryBilling.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoundryBilling.Api.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoundryBilling.Api.Data.Entities.DailyUsageRollup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CompletionTokens")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<long>("PromptTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.HasIndex("Date", "DeploymentId");

                    b.ToTable("DailyUsageRollups", (string)null);
                });

            modelBuilder.Entity("FoundryBilling.Api.Data.Entities.FoundryHub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AzureResourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AzureResourceId")
                        .IsUnique();

                    b.ToTable("FoundryHubs", (string)null);
                });

            modelBuilder.Entity("FoundryBilling.Api.Data.Entities.FoundryProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AzureResourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HubId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HubId");

                    b.ToTable("FoundryProjects", (string)null);
                });

            modelBuilder.Entity("FoundryBilling.Api.Data.Entities.ModelDeployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AzureResourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("DeploymentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HubId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelVersion")
                        .HasColumnType("text");

                    b.Property<string>("SkuName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AzureResourceId")
                        .IsUnique();

                    b.HasIndex("HubId");

                    b.ToTable("ModelDeployments", (string)null);
                });

            modelBuilder.Entity("FoundryBilling.Api.Data.Entities.UsageMetricSlice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CompletionTokens")
                        .HasColumnType("bigint");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid");

                    b.Property<int>("IntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<long>("PromptTokens")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.HasIndex("Timestamp", "DeploymentId");

                    b.ToTable("UsageMetricSlices", (string)null);
                });

            modelBuilder.Entity("FoundryBilling.Api.Data.Entities.DailyUsageRollup", b =>
                {
                    b.HasOne("FoundryBilling.Api.Data.Entities.ModelDeployment", "Deployment")
                        .WithMany("DailyUsageRollups")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("FoundryBilling.Api.Data.Entities.FoundryProject", b =>
                {
                    b.HasOne("FoundryBilling.Api.Data.Entities.FoundryHub", "Hub")
                        .WithMany("Projects")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("FoundryBilling.Api.Data.Entities.ModelDeployment", b =>
                {
                    b.HasOne("FoundryBilling.Api.Data.Entities.FoundryHub", "Hub")
                        .WithMany("Deployments")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("FoundryBilling.Api.Data.Entities.UsageMetricSlice", b =>
                {
                    b.HasOne("FoundryBilling.Api.Data.Entities.ModelDeployment", "Deployment")
                        .WithMany("UsageMetricSlices")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("FoundryBilling.Api.Data.Entities.FoundryHub", b =>
                {
                    b.Navigation("Deployments");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("FoundryBilling.Api.Data.Entities.ModelDeployment", b =>
                {
                    b.Navigation("DailyUsageRollups");

                    b.Navigation("UsageMetricSlices");
                });
#pragma warning restore 612, 618
        }
    }
}
